name: Test Workflow

on:
    push:

jobs:
    test-flow:
        runs-on: Ubuntu-latest

        steps:

            - name: case01
              uses: echo "Case 01 passed successfully"

            - name: |
              uses: echo "Line one of multiline input"
                    echo "Line two of multipline input"

            - name: <
              uses: echo "Compressing
                    mutiple lines
                    in one line"

            - name: Checkout Code
              uses: actions/checkout@v5