name: Test Workflow

on:
    push:

jobs:
    test-flow:
        runs-on: Ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            - name: test_case
              run: | 
                echo "Test Case passed successfully"
                echo "Validation Successfully passed"

            - name: Multi Line Input
              run: |
                echo "Line one of multiline input"
                echo "Line two of multipline input"

            - name: Multiline Compression to one line
              run: < 
                echo "Compressing
                mutiple lines
                in one line"